"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LanguageCode = "en" | "hi" | "gu" | "mr" | "bn" | "ta" | "te" | "sa";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "sa", name: "Sanskrit", nativeName: "संस्कृतम्", flag: "🕉️" },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Brand & Header
    "brand.name": "Swasthya Setu",
    "brand.tagline": "AI-Powered Pre-Consultation for AYUSH Hospitals",
    "brand.opdLive": "OPD Live",
    "header.searchPlaceholder": "Search patient (Name / ID / Mobile)",
    "header.doctorTitle": "Physician (MD Ayurveda)",
    "header.notifications": "Doctor Notifications",
    "header.markAllRead": "Mark all read",
    "header.noPatientFound": "No matching patient in active OPD queue",

    // Navigation
    "nav.home": "Home",
    "nav.patientQueue": "Patient Queue",
    "nav.consultations": "Consultations",
    "nav.doctorListing": "Doctor Listing",
    "nav.patientHistory": "Patient History",
    "nav.reports": "Reports",
    "nav.analytics": "Analytics",
    "nav.settings": "Settings",
    "nav.traditionalWisdom": "Traditional Wisdom",
    "nav.modernIntelligence": "Modern Intelligence",

    // Banner & Badges
    "banner.welcome": "Welcome, Physician",
    "banner.subtitle": "Let's make every consultation more complete and accurate.",
    "badge.voiceTouch": "Voice + Touch Interface",
    "badge.multilingual": "Multilingual (12+ Languages)",
    "badge.ayushSpecific": "AYUSH Specific",
    "badge.documentIntelligence": "Document Intelligence",
    "badge.safeSecure": "Safe & Secure",
    "activePatientLabel": "Active Patient:",

    // Card 1: Patient Case-Taking
    "card1.title": "Patient Case-Taking",
    "card1.subtitle": "The patient shares their concerns in their preferred language, via voice or touch.",
    "card1.ageMale": "Age: 45 | Male",
    "card1.startInteraction": "Start Interaction",
    "card1.step1": "1. Choose Language",
    "card1.step2": "2. Voice / Touch Input",
    "card1.step2Desc": "Patient speaks or selects options",
    "card1.step3": "3. AI Interview",
    "card1.step3Desc": "Adaptive questioning based on response",
    "card1.step4": "4. Case Summary",
    "card1.step4Desc": "Structured data and key findings",

    // Card 2: AI Processing & Data Flow
    "card2.title": "AI Processing & Data Flow",
    "card2.subtitle": "AI extracts, structures and organizes the information.",
    "card2.nlp": "Transcription & NLP",
    "card2.nlpSub": "Real-time speech to text",
    "card2.ayushKb": "AYUSH Knowledge Base",
    "card2.ayushKbSub": "Ayurveda / Siddha Ontologies",
    "card2.caseSheet": "Structured Case Sheet",
    "card2.caseSheetSub": "Standard OPD Format",
    "card2.storage": "Data Storage",
    "card2.storageSub": "ABHA & EHR Compliant",

    // Card 3: Patient Case Sheet (Preview)
    "card3.title": "Patient Case Sheet (Preview)",
    "card3.subtitle": "AI-generated structured summary. Editable by doctor.",
    "card3.viewFullHistory": "View Full History",
    "tab.summary": "Summary",
    "tab.ayushAssessment": "AYUSH Assessment",
    "tab.medicalHistory": "Medical History",
    "tab.reports": "Reports",
    "field.chiefComplaint": "Chief Complaint",
    "field.currentMedicines": "Current Medicines",
    "field.ayushInsights": "AYUSH Insights",
    "field.duration": "Duration",
    "field.allergies": "Allergies",
    "field.prakriti": "Prakriti",
    "field.previousTreatment": "Previous Treatment",
    "field.familyHistory": "Family History",
    "field.agni": "Agni",

    // Card 4: Document Intelligence
    "card4.title": "Document Intelligence",
    "card4.subtitle": "Upload reports and prescriptions. AI extracts and builds a timeline.",
    "card4.dragDrop": "Drag & drop files here",
    "card4.orBrowse": "or click to browse from device",
    "card4.uploadBtn": "Upload Documents",
    "card4.supports": "Supports PDF, JPG, PNG (Max 10MB)",
    "docType.prescription": "Prescription",
    "docType.labReport": "Lab Report",
    "docType.discharge": "Discharge Summary",
    "docType.other": "Other Documents",
    "timeline.title": "Medical Timeline",
    "timeline.chronological": "Chronological",

    // Card 5: Doctor Attention Box
    "card5.title": "Doctor Attention Box",
    "card5.subtitle": "Key points that need your attention.",
    "alert.newSymptom": "New Symptom",
    "alert.sleepDisturbance": "Sleep disturbance",
    "alert.missingReport": "Missing Report",
    "alert.prevPrescription": "Previous prescription",
    "alert.medicineChanged": "Medicine Changed",
    "alert.addedVitaminD": "Added Vitamin D",
    "alert.noCriticalAlerts": "No Critical Alerts",
    "alert.vitalSignsNormal": "Vital signs normal",
    "alert.markDone": "Mark done",
    "alert.resolved": "Resolved ✓",

    // Right Column: Case Completeness & Final Sheet
    "completeness.title": "Case Completeness",
    "completeness.caseComplete": "Case Complete",
    "completeness.itemMissing": "1 item missing: Previous investigations",
    "completeness.askQuestion": "Ask 1 More Question",
    "completeness.infoCollected": "100% Information Collected!",
    "card6.title": "Final Case Sheet",
    "card6.subtitle": "Ready for doctor's review and confirmation.",
    "card6.caseReady": "Case Ready",
    "card6.caseReadyDesc": "All essential information collected. Please review and confirm.",
    "card6.viewFinal": "View Final Case Sheet",
    "card6.editRequest": "Edit / Request More Info",

    // Bottom Ribbon
    "ribbon.smartQuestions": "Smarter Questions",
    "ribbon.smartQuestionsSub": "Asks only what's needed",
    "ribbon.completeHistory": "Complete History",
    "ribbon.completeHistorySub": "Past visits, reports, medicines",
    "ribbon.ayushFocused": "AYUSH Focused",
    "ribbon.ayushFocusedSub": "Dashavidha Pariksha & Prakriti",
    "ribbon.betterDecisions": "Better Decisions",
    "ribbon.betterDecisionsSub": "For doctors and patients",
    "ribbon.slogan": "From first interaction to better care",

    // Patient Dashboard Common
    "patient.greeting": "Namaste,",
    "patient.tagline": "Your personalized AYUSH health & pre-consultation portal",
    "patient.myHealth": "My Health",
    "patient.appointments": "Appointments",
    "patient.medications": "Medications",
    "patient.ayushInsights": "AYUSH Insights",
    "patient.messages": "Messages",
    "patient.readinessGauge": "Case Readiness",
    "patient.bookConsultation": "Book Consultation",
    "patient.uploadReport": "Upload Health Record",
  },
  hi: {
    // Brand & Header
    "brand.name": "स्वास्थ्य सेतु",
    "brand.tagline": "आयुष अस्पतालों के लिए एआई-संचालित प्री-कंसल्टेशन",
    "brand.opdLive": "ओपीडी लाइव",
    "header.searchPlaceholder": "मरीज़ खोजें (नाम / आईडी / मोबाइल)",
    "header.doctorTitle": "चिकित्सक (एमडी आयुर्वेद)",
    "header.notifications": "डॉक्टर सूचनाएं",
    "header.markAllRead": "सभी को पढ़ा हुआ चिह्नित करें",
    "header.noPatientFound": "सक्रिय ओपीडी कतार में कोई मरीज़ नहीं मिला",

    // Navigation
    "nav.home": "मुख्य पृष्ठ",
    "nav.patientQueue": "मरीज़ कतार",
    "nav.consultations": "परामर्श",
    "nav.doctorListing": "डॉक्टर सूची",
    "nav.patientHistory": "मरीज़ इतिहास",
    "nav.reports": "रिपोर्ट्स",
    "nav.analytics": "एनालिटिक्स",
    "nav.settings": "सेटिंग्स",
    "nav.traditionalWisdom": "पारंपरिक ज्ञान",
    "nav.modernIntelligence": "आधुनिक बुद्धिमत्ता",

    // Banner & Badges
    "banner.welcome": "स्वागत है, डॉ. मीरा शर्मा",
    "banner.subtitle": "आइए प्रत्येक परामर्श को अधिक पूर्ण और सटीक बनाएं।",
    "badge.voiceTouch": "आवाज + स्पर्श इंटरफ़ेस",
    "badge.multilingual": "बहुभाषी (12+ भाषाएं)",
    "badge.ayushSpecific": "आयुष विशिष्ट",
    "badge.documentIntelligence": "दस्तावेज़ बुद्धिमत्ता",
    "badge.safeSecure": "सुरक्षित एवं संरक्षित",
    "activePatientLabel": "सक्रिय मरीज़:",

    // Card 1: Patient Case-Taking
    "card1.title": "मरीज़ केस-टेकिंग",
    "card1.subtitle": "मरीज़ अपनी पसंदीदा भाषा में आवाज या स्पर्श के माध्यम से अपनी समस्याएं साझा करता है।",
    "card1.ageMale": "आयु: 45 | पुरुष",
    "card1.startInteraction": "बातचीत शुरू करें",
    "card1.step1": "1. भाषा चुनें",
    "card1.step2": "2. आवाज / स्पर्श इनपुट",
    "card1.step2Desc": "मरीज़ बोलता है या विकल्प चुनता है",
    "card1.step3": "3. एआई साक्षात्कार",
    "card1.step3Desc": "प्रतिक्रिया के आधार पर अनुकूली पूछताछ",
    "card1.step4": "4. केस सारांश",
    "card1.step4Desc": "संरचित डेटा और मुख्य निष्कर्ष",

    // Card 2: AI Processing & Data Flow
    "card2.title": "एआई प्रोसेसिंग और डेटा प्रवाह",
    "card2.subtitle": "एआई जानकारी निकालता, संरचित और व्यवस्थित करता है।",
    "card2.nlp": "प्रतिलेखन और एनएलपी",
    "card2.nlpSub": "रीयल-टाइम आवाज़ से टेक्स्ट",
    "card2.ayushKb": "आयुष ज्ञानकोश",
    "card2.ayushKbSub": "आयुर्वेद / सिद्ध ज्ञान प्रणाली",
    "card2.caseSheet": "संरचित केस शीट",
    "card2.caseSheetSub": "मानक ओपीडी प्रारूप",
    "card2.storage": "डेटा संग्रहण",
    "card2.storageSub": "आभा एवं ईएचआर अनुपालन",

    // Card 3: Patient Case Sheet (Preview)
    "card3.title": "मरीज़ केस शीट (पूर्वावलोकन)",
    "card3.subtitle": "एआई-जनरेटेड संरचित सारांश। डॉक्टर द्वारा संपादन योग्य।",
    "card3.viewFullHistory": "पूर्ण इतिहास देखें",
    "tab.summary": "सारांश",
    "tab.ayushAssessment": "आयुष मूल्यांकन",
    "tab.medicalHistory": "चिकित्सा इतिहास",
    "tab.reports": "रिपोर्ट्स",
    "field.chiefComplaint": "मुख्य शिकायत",
    "field.currentMedicines": "वर्तमान दवाएं",
    "field.ayushInsights": "आयुष अंतर्दृष्टि",
    "field.duration": "अवधि",
    "field.allergies": "एलर्जी",
    "field.prakriti": "प्रकृति",
    "field.previousTreatment": "पिछला उपचार",
    "field.familyHistory": "पारिवारिक इतिहास",
    "field.agni": "अग्नि",

    // Card 4: Document Intelligence
    "card4.title": "दस्तावेज़ बुद्धिमत्ता",
    "card4.subtitle": "रिपोर्ट और पर्चे अपलोड करें। एआई समयरेखा बनाता है।",
    "card4.dragDrop": "फ़ाइलें यहाँ खींचें और छोड़ें",
    "card4.orBrowse": "या डिवाइस से चुनने के लिए क्लिक करें",
    "card4.uploadBtn": "दस्तावेज़ अपलोड करें",
    "card4.supports": "पीडीएफ, जेपीजी, पीएनजी समर्थित (अधिकतम 10MB)",
    "docType.prescription": "पर्चा (प्रिस्क्रिप्शन)",
    "docType.labReport": "लैब रिपोर्ट",
    "docType.discharge": "डिस्चार्ज सारांश",
    "docType.other": "अन्य दस्तावेज़",
    "timeline.title": "चिकित्सा समयरेखा",
    "timeline.chronological": "कालानुक्रमिक",

    // Card 5: Doctor Attention Box
    "card5.title": "डॉक्टर ध्यान बॉक्स",
    "card5.subtitle": "मुख्य बिंदु जिन पर आपके ध्यान की आवश्यकता है।",
    "alert.newSymptom": "नया लक्षण",
    "alert.sleepDisturbance": "नींद में खलल",
    "alert.missingReport": "लापता रिपोर्ट",
    "alert.prevPrescription": "पिछला पर्चा",
    "alert.medicineChanged": "दवा बदली गई",
    "alert.addedVitaminD": "विटामिन डी जोड़ा गया",
    "alert.noCriticalAlerts": "कोई गंभीर चेतावनी नहीं",
    "alert.vitalSignsNormal": "वाइटल संकेत सामान्य",
    "alert.markDone": "पूर्ण चिह्नित करें",
    "alert.resolved": "सुलझाया गया ✓",

    // Right Column: Case Completeness & Final Sheet
    "completeness.title": "केस पूर्णता",
    "completeness.caseComplete": "केस पूर्ण",
    "completeness.itemMissing": "1 जानकारी शेष: पिछली जांच (इन्वेस्टिगेशन)",
    "completeness.askQuestion": "1 और प्रश्न पूछें",
    "completeness.infoCollected": "100% जानकारी एकत्र!",
    "card6.title": "अंतिम केस शीट",
    "card6.subtitle": "डॉक्टर की समीक्षा और पुष्टि के लिए तैयार।",
    "card6.caseReady": "केस तैयार",
    "card6.caseReadyDesc": "सभी आवश्यक जानकारी एकत्र की गई। कृपया समीक्षा करें और पुष्टि करें।",
    "card6.viewFinal": "अंतिम केस शीट देखें",
    "card6.editRequest": "संपादित करें / अधिक जानकारी मांगें",

    // Bottom Ribbon
    "ribbon.smartQuestions": "स्मार्ट प्रश्न",
    "ribbon.smartQuestionsSub": "केवल वही पूछता है जो आवश्यक है",
    "ribbon.completeHistory": "पूर्ण इतिहास",
    "ribbon.completeHistorySub": "पिछली मुलाकातें, रिपोर्ट, दवाएं",
    "ribbon.ayushFocused": "आयुष केंद्रित",
    "ribbon.ayushFocusedSub": "दशविध परीक्षा एवं प्रकृति",
    "ribbon.betterDecisions": "बेहतर निर्णय",
    "ribbon.betterDecisionsSub": "डॉक्टरों और मरीजों के लिए",
    "ribbon.slogan": "पहली बातचीत से बेहतर देखभाल तक",

    // Patient Dashboard Common
    "patient.greeting": "नमस्ते,",
    "patient.tagline": "आपका व्यक्तिगत आयुष स्वास्थ्य और प्री-कंसल्टेशन पोर्टल",
    "patient.myHealth": "मेरा स्वास्थ्य",
    "patient.appointments": "अपॉइंटमेंट्स",
    "patient.medications": "दवाइयां",
    "patient.ayushInsights": "आयुष अंतर्दृष्टि",
    "patient.messages": "संदेश",
    "patient.readinessGauge": "केस तत्परता",
    "patient.bookConsultation": "परामर्श बुक करें",
    "patient.uploadReport": "स्वास्थ्य रिकॉर्ड अपलोड करें",
  },
  gu: {
    "brand.name": "સ્વાસ્થ્ય સેતુ",
    "brand.tagline": "આયુષ હોસ્પિટલો માટે એઆઈ આધારિત પૂર્વ-પરામર્શ",
    "brand.opdLive": "ઓપીડી લાઈવ",
    "header.searchPlaceholder": "દર્દી શોધો (નામ / આઈડી / મોબાઈલ)",
    "header.doctorTitle": "તબીબ (એમડી આયુર્વેદ)",
    "header.notifications": "ડૉક્ટર સૂચનાઓ",
    "header.markAllRead": "બધા વાંચેલા ચિહ્નિત કરો",
    "header.noPatientFound": "સક્રિય ઓપીડી કતારમાં કોઈ દર્દી મળ્યા નથી",

    "nav.home": "મુખ્ય પૃષ્ઠ",
    "nav.patientQueue": "દર્દીઓની કતાર",
    "nav.consultations": "પરામર્શ",
    "nav.patientHistory": "દર્દી ઇતિહાસ",
    "nav.reports": "રિપોર્ટ્સ",
    "nav.analytics": "એનાલિટિક્સ",
    "nav.settings": "સેટિંગ્સ",
    "nav.traditionalWisdom": "પરંપરાગત જ્ઞાન",
    "nav.modernIntelligence": "આધુનિક બુદ્ધિમત્તા",

    "banner.welcome": "સ્વાગત છે, ડૉ. મીરા શર્મા",
    "banner.subtitle": "ચાલો દરેક પરામર્શને વધુ સંપૂર્ણ અને સચોટ બનાવીએ.",
    "badge.voiceTouch": "અવાજ + સ્પર્શ ઇન્ટરફેસ",
    "badge.multilingual": "બહુભાષી (12+ ભાષાઓ)",
    "badge.ayushSpecific": "આયુષ વિશિષ્ટ",
    "badge.documentIntelligence": "દસ્તાવેજ બુદ્ધિમત્તા",
    "badge.safeSecure": "સલામત અને સુરક્ષિત",
    "activePatientLabel": "સક્રિય દર્દી:",

    "card1.title": "દર્દી કેસ-ટેકિંગ",
    "card1.subtitle": "દર્દી તેમની પસંદગીની ભાષામાં અવાજ અથવા સ્પર્શ દ્વારા તેમની ચિંતાઓ શેર કરે છે.",
    "card1.ageMale": "ઉંમર: 45 | પુરુષ",
    "card1.startInteraction": "વાર્તાલાપ શરૂ કરો",
    "card1.step1": "1. ભાષા પસંદ કરો",
    "card1.step2": "2. અવાજ / સ્પર્શ ઇનપુટ",
    "card1.step2Desc": "દર્દી બોલે છે અથવા વિકલ્પો પસંદ કરે છે",
    "card1.step3": "3. એઆઈ ઇન્ટરવ્યુ",
    "card1.step3Desc": "પ્રતિભાવ પર આધારિત પ્રશ્નોત્તરી",
    "card1.step4": "4. કેસ સારાંશ",
    "card1.step4Desc": "સંરચિત ડેટા અને મુખ્ય તારણો",

    "card2.title": "એઆઈ પ્રોસેસિંગ અને ડેટા પ્રવાહ",
    "card2.subtitle": "એઆઈ માહિતી કાઢે છે, સંરચિત કરે છે અને ગોઠવે છે.",
    "card2.nlp": "ટ્રાન્સક્રિપ્શન અને એનએલપી",
    "card2.nlpSub": "રીયલ-ટાઇમ અવાજમાંથી ટેક્સ્ટ",
    "card2.ayushKb": "આયુષ જ્ઞાનકોશ",
    "card2.ayushKbSub": "આયુર્વેદ જ્ઞાન પ્રણાલી",
    "card2.caseSheet": "સંરચિત કેસ શીટ",
    "card2.caseSheetSub": "માનક ઓપીડી ફોર્મેટ",
    "card2.storage": "ડેટા સંગ્રહ",
    "card2.storageSub": "આભા અને ઇએચઆર સુસંગત",

    "card3.title": "દર્દી કેસ શીટ (પૂર્વાવલોકન)",
    "card3.subtitle": "એઆઈ-જનરેટેડ સંરચિત સારાંશ. ડૉક્ટર દ્વારા સંપાદન યોગ્ય.",
    "card3.viewFullHistory": "સંપૂર્ણ ઇતિહાસ જુઓ",
    "tab.summary": "સારાંશ",
    "tab.ayushAssessment": "આયુષ મૂલ્યાંકન",
    "tab.medicalHistory": "તબીબી ઇતિહાસ",
    "tab.reports": "રિપોર્ટ્સ",
    "field.chiefComplaint": "મુખ્ય ફરિયાદ",
    "field.currentMedicines": "હાલની દવાઓ",
    "field.ayushInsights": "આયુષ આંતરદ્રષ્ટિ",
    "field.duration": "સમયગાળો",
    "field.allergies": "એલર્જી",
    "field.prakriti": "પ્રકૃતિ",
    "field.previousTreatment": "અગાઉની સારવાર",
    "field.familyHistory": "પારિવારિક ઇતિહાસ",
    "field.agni": "અગ્નિ",

    "card4.title": "દસ્તાવેજ બુદ્ધિમત્તા",
    "card4.subtitle": "રિપોર્ટ્સ અને પ્રિસ્ક્રિપ્શન અપલોડ કરો. એઆઈ ટાઇમલાઇન બનાવે છે.",
    "card4.dragDrop": "ફાઇલો અહીં ખેંચો અને મૂકો",
    "card4.orBrowse": "અથવા ડિવાઇસમાંથી પસંદ કરવા ક્લિક કરો",
    "card4.uploadBtn": "દસ્તાવેજ અપલોડ કરો",
    "card4.supports": "પીડીએફ, જેપીજી, પીએનજી સપોર્ટેડ (મહત્તમ 10MB)",
    "docType.prescription": "પ્રિસ્ક્રિપ્શન",
    "docType.labReport": "લેબ રિપોર્ટ",
    "docType.discharge": "ડિસ્ચાર્જ સારાંશ",
    "docType.other": "અન્ય દસ્તાવેજો",
    "timeline.title": "તબીબી ટાઇમલાઇન",
    "timeline.chronological": "કાળક્રમિક",

    "card5.title": "ડૉક્ટર ધ્યાન બોક્સ",
    "card5.subtitle": "મુખ્ય મુદ્દાઓ કે જેના પર તમારા ધ્યાનની જરૂર છે.",
    "alert.newSymptom": "નવું લક્ષણ",
    "alert.sleepDisturbance": "ઊંઘમાં ખલેલ",
    "alert.missingReport": "ગુમ થયેલ રિપોર્ટ",
    "alert.prevPrescription": "અગાઉનું પ્રિસ્ક્રિપ્શન",
    "alert.medicineChanged": "દવા બદલાઈ",
    "alert.addedVitaminD": "વિટામિન ડી ઉમેરાયું",
    "alert.noCriticalAlerts": "કોઈ ગંભીર ચેતવણી નથી",
    "alert.vitalSignsNormal": "મહત્વપૂર્ણ સંકેતો સામાન્ય",
    "alert.markDone": "પૂર્ણ ચિહ્નિત કરો",
    "alert.resolved": "ઉકેલાયેલ ✓",

    "completeness.title": "કેસ પૂર્ણતા",
    "completeness.caseComplete": "કેસ પૂર્ણ",
    "completeness.itemMissing": "1 વિગત ખૂટે છે: અગાઉની તપાસ",
    "completeness.askQuestion": "વધુ 1 પ્રશ્ન પૂછો",
    "completeness.infoCollected": "100% માહિતી એકત્રિત!",
    "card6.title": "અંતિમ કેસ શીટ",
    "card6.subtitle": "ડૉક્ટરની સમીક્ષા અને પુષ્ટિ માટે તૈયાર.",
    "card6.caseReady": "કેસ તૈયાર",
    "card6.caseReadyDesc": "તમામ આવશ્યક માહિતી એકત્રિત. કૃપા કરીને સમીક્ષા કરો અને પુષ્ટિ કરો.",
    "card6.viewFinal": "અંતિમ કેસ શીટ જુઓ",
    "card6.editRequest": "સંપાદિત કરો / વધુ માહિતી માગો",

    "ribbon.smartQuestions": "સ્માર્ટ પ્રશ્નો",
    "ribbon.smartQuestionsSub": "ફક્ત જે જરૂરી છે તે જ પૂછે છે",
    "ribbon.completeHistory": "સંપૂર્ણ ઇતિહાસ",
    "ribbon.completeHistorySub": "ભૂતકાળની મુલાકાતો, રિપોર્ટ્સ, દવાઓ",
    "ribbon.ayushFocused": "આયુષ કેન્દ્રિત",
    "ribbon.ayushFocusedSub": "દશવિધ પરીક્ષા અને પ્રકૃતિ",
    "ribbon.betterDecisions": "વધુ સારા નિર્ણયો",
    "ribbon.betterDecisionsSub": "ડૉક્ટરો અને દર્દીઓ માટે",
    "ribbon.slogan": "પ્રથમ ક્રિયાપ્રતિક્રિયાથી વધુ સારી સંભાળ સુધી",

    "patient.greeting": "નમસ્તે,",
    "patient.tagline": "તમારું વ્યક્તિગત આયુષ આરોગ્ય પોર્ટલ",
    "patient.myHealth": "મારું આરોગ્ય",
    "patient.appointments": "મુલાકાતો",
    "patient.medications": "દવાઓ",
    "patient.ayushInsights": "આયુષ આંતરદ્રષ્ટિ",
    "patient.messages": "સંદેશાઓ",
    "patient.readinessGauge": "કેસ સજ્જતા",
    "patient.bookConsultation": "પરામર્શ બુક કરો",
    "patient.uploadReport": "રેકોર્ડ અપલોડ કરો",
  },
  mr: {
    "brand.name": "स्वास्थ्य सेतु",
    "brand.tagline": "आयुष रुग्णालयांसाठी एआय-आधारित पूर्व-परामर्श",
    "brand.opdLive": "ओपीडी लाईव्ह",
    "header.searchPlaceholder": "रुग्ण शोधा (नाव / आयडी / मोबाईल)",
    "header.doctorTitle": "वैद्य (एमडी आयुर्वेद)",
    "header.notifications": "डॉक्टर सूचना",
    "header.markAllRead": "सर्व वाचलेले चिन्हांकित करा",
    "header.noPatientFound": "सक्रिय ओपीडी रांगेत कोणताही रुग्ण आढळला नाही",

    "nav.home": "मुख्य पृष्ठ",
    "nav.patientQueue": "रुग्ण रांग",
    "nav.consultations": "सल्लामसलत",
    "nav.patientHistory": "रुग्ण इतिहास",
    "nav.reports": "अहवाल",
    "nav.analytics": "विश्लेषण",
    "nav.settings": "सेटिंग्ज",
    "nav.traditionalWisdom": "पारंपारिक ज्ञान",
    "nav.modernIntelligence": "आधुनिक बुद्धिमत्ता",

    "banner.welcome": "स्वागत आहे, डॉ. मीरा शर्मा",
    "banner.subtitle": "चला प्रत्येक सल्लामसलत अधिक परिपूर्ण आणि अचूक करूया.",
    "badge.voiceTouch": "आवाज + स्पर्श इंटरफेस",
    "badge.multilingual": "बहुभाषिक (12+ भाषा)",
    "badge.ayushSpecific": "आयुष विशिष्ट",
    "badge.documentIntelligence": "दस्तऐवज बुद्धिमत्ता",
    "badge.safeSecure": "सुरक्षित आणि संरक्षित",
    "activePatientLabel": "सक्रिय रुग्ण:",

    "card1.title": "रुग्ण केस-टेकिंग",
    "card1.subtitle": "रुग्ण त्यांच्या पसंतीच्या भाषेत आवाज किंवा स्पर्शाद्वारे त्यांच्या समस्या सामायिक करतो.",
    "card1.ageMale": "वय: 45 | पुरुष",
    "card1.startInteraction": "संवाद सुरू करा",
    "card1.step1": "1. भाषा निवडा",
    "card1.step2": "2. आवाज / स्पर्श इनपुट",
    "card1.step2Desc": "रुग्ण बोलतो किंवा पर्याय निवडतो",
    "card1.step3": "3. एआय मुलाखत",
    "card1.step3Desc": "प्रतिसादावर आधारित अनुकूल प्रश्न विचारणे",
    "card1.step4": "4. केस सारांश",
    "card1.step4Desc": "संरचित डेटा आणि मुख्य निष्कर्ष",

    "card2.title": "एआय प्रक्रिया आणि डेटा प्रवाह",
    "card2.subtitle": "एआय माहिती काढतो, संरचित करतो आणि व्यवस्थापित करतो.",
    "card2.nlp": "ट्रान्सक्रिप्शन आणि एनएलपी",
    "card2.nlpSub": "रिअल-टाइम आवाजातून मजकूर",
    "card2.ayushKb": "आयुष ज्ञानकोश",
    "card2.ayushKbSub": "आयुर्वेद ज्ञान प्रणाली",
    "card2.caseSheet": "संरचित केस शीट",
    "card2.caseSheetSub": "प्रमाणित ओपीडी स्वरूप",
    "card2.storage": "डेटा स्टोरेज",
    "card2.storageSub": "आभा आणि ईएचआर अनुपालन",

    "card3.title": "रुग्ण केस शीट (पूर्वावलोकन)",
    "card3.subtitle": "एआय-व्युत्पन्न संरचित सारांश. डॉक्टरांद्वारे संपादन करण्यायोग्य.",
    "card3.viewFullHistory": "पूर्ण इतिहास पहा",
    "tab.summary": "सारांश",
    "tab.ayushAssessment": "आयुष मूल्यांकन",
    "tab.medicalHistory": "वैद्यकीय इतिहास",
    "tab.reports": "अहवाल",
    "field.chiefComplaint": "मुख्य तक्रार",
    "field.currentMedicines": "सध्याची औषधे",
    "field.ayushInsights": "आयुष अंतर्दृष्टी",
    "field.duration": "कालावधी",
    "field.allergies": "ऍलर्जी",
    "field.prakriti": "प्रकृती",
    "field.previousTreatment": "मागील उपचार",
    "field.familyHistory": "कौटुंबिक इतिहास",
    "field.agni": "अग्नी",

    "card4.title": "दस्तऐवज बुद्धिमत्ता",
    "card4.subtitle": "अहवाल आणि प्रिस्क्रिप्शन अपलोड करा. एआय टाइमलाइन तयार करतो.",
    "card4.dragDrop": "फायली येथे ड्रॅग आणि ड्रॉप करा",
    "card4.orBrowse": "किंवा डिव्हाइसवरून निवडण्यासाठी क्लिक करा",
    "card4.uploadBtn": "दस्तऐवज अपलोड करा",
    "card4.supports": "पीडीएफ, जेपीजी, पीएनजी समर्थित (कमाल 10MB)",
    "docType.prescription": "प्रिस्क्रिप्शन",
    "docType.labReport": "लॅब अहवाल",
    "docType.discharge": "डिस्चार्ज सारांश",
    "docType.other": "इतर कागदपत्रे",
    "timeline.title": "वैद्यकीय टाइमलाइन",
    "timeline.chronological": "कालक्रमानुसार",

    "card5.title": "डॉक्टर लक्ष बॉक्स",
    "card5.subtitle": "मुख्य मुद्दे ज्यावर आपल्या लक्षाची आवश्यकता आहे.",
    "alert.newSymptom": "नवीन लक्षण",
    "alert.sleepDisturbance": "झोपेत अडथळा",
    "alert.missingReport": "गहाळ अहवाल",
    "alert.prevPrescription": "मागील प्रिस्क्रिप्शन",
    "alert.medicineChanged": "औषध बदलले",
    "alert.addedVitaminD": "व्हिटॅमिन डी जोडले",
    "alert.noCriticalAlerts": "कोणतीही गंभीर सूचना नाही",
    "alert.vitalSignsNormal": "महत्त्वपूर्ण चिन्हे सामान्य",
    "alert.markDone": "पूर्ण चिन्हांकित करा",
    "alert.resolved": "निराकरण झाले ✓",

    "completeness.title": "केस पूर्णता",
    "completeness.caseComplete": "केस पूर्ण",
    "completeness.itemMissing": "1 माहिती बाकी: मागील तपासणी",
    "completeness.askQuestion": "आणखी 1 प्रश्न विचारा",
    "completeness.infoCollected": "100% माहिती संकलित!",
    "card6.title": "अंतिम केस शीट",
    "card6.subtitle": "डॉक्टरांच्या पुनरावलोकन आणि पुष्टीकरणासाठी तयार.",
    "card6.caseReady": "केस तयार",
    "card6.caseReadyDesc": "सर्व आवश्यक माहिती गोळा केली. कृपया पुनरावलोकन करा आणि पुष्टी करा.",
    "card6.viewFinal": "अंतिम केस शीट पहा",
    "card6.editRequest": "संपादित करा / अधिक माहिती विचारा",

    "ribbon.smartQuestions": "स्मार्ट प्रश्न",
    "ribbon.smartQuestionsSub": "फक्त जे आवश्यक आहे तेच विचारते",
    "ribbon.completeHistory": "पूर्ण इतिहास",
    "ribbon.completeHistorySub": "मागील भेटी, अहवाल, औषधे",
    "ribbon.ayushFocused": "आयुष केंद्रित",
    "ribbon.ayushFocusedSub": "दशविध परीक्षा आणि प्रकृती",
    "ribbon.betterDecisions": "अधिक चांगले निर्णय",
    "ribbon.betterDecisionsSub": "डॉक्टर आणि रुग्णांसाठी",
    "ribbon.slogan": "पहिल्या संवादापासून चांगल्या काळजीपर्यंत",

    "patient.greeting": "नमस्ते,",
    "patient.tagline": "तुमचे वैयक्तिकृत आयुष आरोग्य पोर्टल",
    "patient.myHealth": "माझे आरोग्य",
    "patient.appointments": "अपॉइंटमेंट्स",
    "patient.medications": "औषधे",
    "patient.ayushInsights": "आयुष अंतर्दृष्टी",
    "patient.messages": "संदेश",
    "patient.readinessGauge": "केस सज्जता",
    "patient.bookConsultation": "सल्लामसलत बुक करा",
    "patient.uploadReport": "आरोग्य नोंद अपलोड करा",
  },
  bn: {
    "brand.name": "স্বাস্থ্য সেতু",
    "brand.tagline": "আয়ুষ হাসপাতালের জন্য এআই-চালিত প্রাক-পরামর্শ",
    "brand.opdLive": "ওপিডি লাইভ",
    "header.searchPlaceholder": "রোগী অনুসন্ধান করুন (নাম / আইডি / মোবাইল)",
    "header.doctorTitle": "চিকিৎসক (এমডি আয়ুর্বেদ)",
    "header.notifications": "ডাক্তার বিজ্ঞপ্তি",
    "header.markAllRead": "সব পঠিত হিসেবে চিহ্নিত করুন",
    "header.noPatientFound": "সক্রিয় ওপিডি সারিতে কোন রোগী পাওয়া যায়নি",

    "nav.home": "হোম",
    "nav.patientQueue": "রোগীর সারি",
    "nav.consultations": "পরামর্শ",
    "nav.patientHistory": "রোগীর ইতিহাস",
    "nav.reports": "রিপোর্ট",
    "nav.analytics": "বিশ্লেষণ",
    "nav.settings": "সেটিংস",
    "nav.traditionalWisdom": "ঐতিহ্যবাহী প্রজ্ঞা",
    "nav.modernIntelligence": "আধুনিক বুদ্ধিমত্তা",

    "banner.welcome": "স্বাগতম, ডাঃ মীরা শর্মা",
    "banner.subtitle": "আসুন প্রতিটি পরামর্শকে আরও সম্পূর্ণ এবং নির্ভুল করি।",
    "badge.voiceTouch": "ভয়েস + টাচ ইন্টারফেস",
    "badge.multilingual": "বহুভাষিক (১২+ ভাষা)",
    "badge.ayushSpecific": "আয়ুষ নির্দিষ্ট",
    "badge.documentIntelligence": "ডকুমেন্ট ইন্টেলিজেন্স",
    "badge.safeSecure": "নিরাপদ ও সুরক্ষিত",
    "activePatientLabel": "সক্রিয় রোগী:",

    "card1.title": "রোগীর কেস-টেকিং",
    "card1.subtitle": "রোগী তাদের পছন্দের ভাষায় ভয়েস বা টাচের মাধ্যমে উদ্বেগ প্রকাশ করেন।",
    "card1.ageMale": "বয়স: ৪৫ | পুরুষ",
    "card1.startInteraction": "কথোপকথন শুরু করুন",
    "card1.step1": "১. ভাষা নির্বাচন করুন",
    "card1.step2": "২. ভয়েস / টাচ ইনপুট",
    "card1.step2Desc": "রোগী কথা বলেন বা বিকল্প নির্বাচন করেন",
    "card1.step3": "৩. এআই ইন্টারভিউ",
    "card1.step3Desc": "প্রতিক্রিয়ার উপর ভিত্তি করে অভিযোজিত প্রশ্ন",
    "card1.step4": "৪. কেস সারাংশ",
    "card1.step4Desc": "কাঠামোগত তথ্য এবং প্রধান ফলাফল",

    "card2.title": "এআই প্রসেসিং ও ডেটা ফ্লো",
    "card2.subtitle": "এআই তথ্য বের করে, গঠন করে এবং সংগঠিত করে।",
    "card2.nlp": "ট্রান্সক্রিপশন ও এনএলপি",
    "card2.nlpSub": "রিয়েল-টাইম স্পিচ থেকে টেক্সট",
    "card2.ayushKb": "আয়ুষ নলেজ বেস",
    "card2.ayushKbSub": "আয়ুর্বেদ জ্ঞান ব্যবস্থা",
    "card2.caseSheet": "স্ট্রাকচার্ড কেস শিট",
    "card2.caseSheetSub": "স্ট্যান্ডার্ড ওপিডি ফরম্যাট",
    "card2.storage": "ডেটা স্টোরেজ",
    "card2.storageSub": "আভা ও ইএইচআর অনুবর্তী",

    "card3.title": "রোগীর কেস শিট (প্রাকদর্শন)",
    "card3.subtitle": "এআই-জেনারেটেড সংক্ষিপ্তসার। ডাক্তার দ্বারা সম্পাদনাযোগ্য।",
    "card3.viewFullHistory": "সম্পূর্ণ ইতিহাস দেখুন",
    "tab.summary": "সারাংশ",
    "tab.ayushAssessment": "আয়ুষ মূল্যায়ন",
    "tab.medicalHistory": "চিকিৎসা ইতিহাস",
    "tab.reports": "রিপোর্ট",
    "field.chiefComplaint": "প্রধান সমস্যা",
    "field.currentMedicines": "বর্তমান ওষুধ",
    "field.ayushInsights": "আয়ুষ অন্তর্দৃষ্টি",
    "field.duration": "সময়কাল",
    "field.allergies": "অ্যালার্জি",
    "field.prakriti": "প্রকৃতি",
    "field.previousTreatment": "পূর্ববর্তী চিকিৎসা",
    "field.familyHistory": "পারিবারিক ইতিহাস",
    "field.agni": "অগ্নি",

    "card4.title": "ডকুমেন্ট ইন্টেলিজেন্স",
    "card4.subtitle": "রিপোর্ট এবং প্রেসক্রিপশন আপলোড করুন। এআই টাইমলাইন তৈরি করে।",
    "card4.dragDrop": "এখানে ফাইল টেনে আনুন",
    "card4.orBrowse": "অথবা ডিভাইস থেকে বেছে নিতে ক্লিক করুন",
    "card4.uploadBtn": "ডকুমেন্ট আপলোড করুন",
    "card4.supports": "পিডিএফ, জেপিজি, পিএনজি সমর্থিত (সর্বোচ্চ ১০MB)",
    "docType.prescription": "প্রেসক্রিপশন",
    "docType.labReport": "ল্যাব রিপোর্ট",
    "docType.discharge": "ডিসচার্জ সারাংশ",
    "docType.other": "অন্যান্য নথি",
    "timeline.title": "মেডিকেল টাইমলাইন",
    "timeline.chronological": "কালানুক্রমিক",

    "card5.title": "ডাক্তার মনোযোগ বাক্স",
    "card5.subtitle": "প্রধান পয়েন্ট যা আপনার মনোযোগ প্রয়োজন।",
    "alert.newSymptom": "নতুন উপসর্গ",
    "alert.sleepDisturbance": "ঘুমের ব্যাঘাত",
    "alert.missingReport": "অনুপস্থিত রিপোর্ট",
    "alert.prevPrescription": "আগের প্রেসক্রিপশন",
    "alert.medicineChanged": "ওষুধ পরিবর্তিত",
    "alert.addedVitaminD": "ভিটামিন ডি যুক্ত করা হয়েছে",
    "alert.noCriticalAlerts": "কোন জটিল সতর্কতা নেই",
    "alert.vitalSignsNormal": "গুরুত্বপূর্ণ লক্ষণ স্বাভাবিক",
    "alert.markDone": "সম্পন্ন চিহ্নিত করুন",
    "alert.resolved": "সমাধান হয়েছে ✓",

    "completeness.title": "কেস সম্পূর্ণতা",
    "completeness.caseComplete": "কেস সম্পূর্ণ",
    "completeness.itemMissing": "১টি তথ্য বাকি: পূর্ববর্তী পরীক্ষা",
    "completeness.askQuestion": "আরও ১টি প্রশ্ন করুন",
    "completeness.infoCollected": "১০০% তথ্য সংগৃহীত!",
    "card6.title": "চূড়ান্ত কেস শিট",
    "card6.subtitle": "ডাক্তারের পর্যালোচনা এবং নিশ্চিতকরণের জন্য প্রস্তুত।",
    "card6.caseReady": "কেস প্রস্তুত",
    "card6.caseReadyDesc": "সমস্ত প্রয়োজনীয় তথ্য সংগৃহীত। পর্যালোচনা এবং নিশ্চিত করুন।",
    "card6.viewFinal": "চূড়ান্ত কেস শিট দেখুন",
    "card6.editRequest": "সম্পাদনা করুন / আরও তথ্য চান",

    "ribbon.smartQuestions": "স্মার্ট প্রশ্ন",
    "ribbon.smartQuestionsSub": "কেবল যা প্রয়োজন তা জিজ্ঞাসা করে",
    "ribbon.completeHistory": "সম্পূর্ণ ইতিহাস",
    "ribbon.completeHistorySub": "অতীত সাক্ষাৎ, রিপোর্ট, ওষুধ",
    "ribbon.ayushFocused": "আয়ুষ ফোকাসড",
    "ribbon.ayushFocusedSub": "দশবিধ পরীক্ষা এবং প্রকৃতি",
    "ribbon.betterDecisions": "উন্নত সিদ্ধান্ত",
    "ribbon.betterDecisionsSub": "ডাক্তার এবং রোগীদের জন্য",
    "ribbon.slogan": "প্রথম মিথস্ক্রিয়া থেকে উন্নত যত্ন",

    "patient.greeting": "নমস্কার,",
    "patient.tagline": "আপনার ব্যক্তিগতকৃত আয়ুষ স্বাস্থ্য পোর্টাল",
    "patient.myHealth": "আমার স্বাস্থ্য",
    "patient.appointments": "সাক্ষাৎকার",
    "patient.medications": "ওষুধ",
    "patient.ayushInsights": "আয়ুষ অন্তর্দৃষ্টি",
    "patient.messages": "বার্তা",
    "patient.readinessGauge": "কেস প্রস্তুতি",
    "patient.bookConsultation": "পরামর্শ বুক করুন",
    "patient.uploadReport": "স্বাস্থ্য রেকর্ড আপলোড করুন",
  },
  ta: {
    "brand.name": "சுவஸ்த்ய சேது",
    "brand.tagline": "ஆயுஷ் மருத்துவமனைகளுக்கான AI-இயங்கும் முன்-ஆலோசனை",
    "brand.opdLive": "OPD நேரலை",
    "header.searchPlaceholder": "நோயாளி தேடல் (பெயர் / ID / மொபைல்)",
    "header.doctorTitle": "மருத்துவர் (MD ஆயுர்வேதம்)",
    "header.notifications": "மருத்துவர் அறிவிப்புகள்",
    "header.markAllRead": "அனைத்தையும் படித்ததாகக் குறிக்கவும்",
    "header.noPatientFound": "செயலில் உள்ள OPD வரிசையில் நோயாளிகள் இல்லை",

    "nav.home": "முகப்பு",
    "nav.patientQueue": "நோயாளி வரிசை",
    "nav.consultations": "ஆலோசனைகள்",
    "nav.patientHistory": "நோயாளி வரலாறு",
    "nav.reports": "அறிக்கைகள்",
    "nav.analytics": "பகுப்பாய்வு",
    "nav.settings": "அமைப்புகள்",
    "nav.traditionalWisdom": "பாரம்பரிய ஞானம்",
    "nav.modernIntelligence": "நவீன நுண்ணறிவு",

    "banner.welcome": "வரவேற்கிறோம், டாக்டர் மீரா சர்மா",
    "banner.subtitle": "ஒவ்வொரு ஆலோசனையையும் முழுமையாகவும் துல்லியமாகவும் மாற்றுவோம்.",
    "badge.voiceTouch": "குரல் + தொடு இடைமுகம்",
    "badge.multilingual": "பன்மொழி (12+ மொழிகள்)",
    "badge.ayushSpecific": "ஆயுஷ் சிறப்பு",
    "badge.documentIntelligence": "ஆவண நுண்ணறிவு",
    "badge.safeSecure": "பாதுகாப்பானது",
    "activePatientLabel": "செயலில் உள்ள நோயாளி:",

    "card1.title": "நோயாளி வழக்கு பதிவு",
    "card1.subtitle": "நோயாளி தங்களுக்கு விருப்பமான மொழியில் குரல் அல்லது தொடுதல் மூலம் பகிர்கிறார்.",
    "card1.ageMale": "வயது: 45 | ஆண்",
    "card1.startInteraction": "உரையாடலைத் தொடங்கு",
    "card1.step1": "1. மொழி தேர்வு",
    "card1.step2": "2. குரல் / தொடு உள்ளீடு",
    "card1.step2Desc": "நோயாளி பேசுகிறார் அல்லது தேர்வு செய்கிறார்",
    "card1.step3": "3. AI நேர்காணல்",
    "card1.step3Desc": "பதிலின் அடிப்படையில் கேள்விகள்",
    "card1.step4": "4. வழக்கு சுருக்கம்",
    "card1.step4Desc": "கட்டமைக்கப்பட்ட தரவு மற்றும் முடிவுகள்",

    "card2.title": "AI செயலாக்கம் & தரவு ஓட்டம்",
    "card2.subtitle": "AI தகவலைப் பிரித்தெடுத்து, கட்டமைத்து ஒழுங்கமைக்கிறது.",
    "card2.nlp": "டிரான்ஸ்கிரிப்ஷன் & NLP",
    "card2.nlpSub": "நேரலை பேச்சு முதல் உரை வரை",
    "card2.ayushKb": "ஆயுஷ் அறிவு தளம்",
    "card2.ayushKbSub": "ஆயுர்வேத அறிவு கட்டமைப்பு",
    "card2.caseSheet": "வழக்கு தாள்",
    "card2.caseSheetSub": "நிலையான OPD வடிவம்",
    "card2.storage": "தரவு சேமிப்பு",
    "card2.storageSub": "ABHA & EHR இணக்கமானது",

    "card3.title": "நோயாளி வழக்கு தாள் (முன்னோட்டம்)",
    "card3.subtitle": "AI-உருவாக்கிய சுருக்கம். மருத்துவரால் திருத்தக்கூடியது.",
    "card3.viewFullHistory": "முழு வரலாற்றைக் காண்க",
    "tab.summary": "சுருக்கம்",
    "tab.ayushAssessment": "ஆயுஷ் மதிப்பீடு",
    "tab.medicalHistory": "மருத்துவ வரலாறு",
    "tab.reports": "அறிக்கைகள்",
    "field.chiefComplaint": "முக்கிய புகார்",
    "field.currentMedicines": "தற்போதைய மருந்துகள்",
    "field.ayushInsights": "ஆயுஷ் நுண்ணறிவு",
    "field.duration": "கால அளவு",
    "field.allergies": "ஒவ்வாமை",
    "field.prakriti": "பிரகிருதி",
    "field.previousTreatment": "முந்தைய சிகிச்சை",
    "field.familyHistory": "குடும்ப வரலாறு",
    "field.agni": "அக்னி",

    "card4.title": "ஆவண நுண்ணறிவு",
    "card4.subtitle": "அறிக்கைகளை பதிவேற்றவும். AI காலவரிசையை உருவாக்குகிறது.",
    "card4.dragDrop": "கோப்புகளை இங்கே இழுத்துப் போடுங்கள்",
    "card4.orBrowse": "அல்லது சாதனத்திலிருந்து உலாவ கிளிக் செய்க",
    "card4.uploadBtn": "ஆவணங்களைப் பதிவேற்று",
    "card4.supports": "PDF, JPG, PNG (அதிகபட்சம் 10MB)",
    "docType.prescription": "மருந்துச் சீட்டு",
    "docType.labReport": "ஆய்வக அறிக்கை",
    "docType.discharge": "வெளியேற்ற சுருக்கம்",
    "docType.other": "பிற ஆவணங்கள்",
    "timeline.title": "மருத்துவ காலவரிசை",
    "timeline.chronological": "காலவரிசைப்படி",

    "card5.title": "மருத்துவர் கவனப் பெட்டி",
    "card5.subtitle": "உங்கள் கவனம் தேவைப்படும் முக்கிய குறிப்புகள்.",
    "alert.newSymptom": "புதிய அறிகுறி",
    "alert.sleepDisturbance": "தூக்கக் கலக்கம்",
    "alert.missingReport": "காணாமல் போன அறிக்கை",
    "alert.prevPrescription": "முந்தைய மருந்துச்சீட்டு",
    "alert.medicineChanged": "மருந்து மாற்றப்பட்டது",
    "alert.addedVitaminD": "வைட்டமின் D சேர்க்கப்பட்டது",
    "alert.noCriticalAlerts": "முக்கிய எச்சரிக்கைகள் இல்லை",
    "alert.vitalSignsNormal": "முக்கிய அறிகுறிகள் இயல்பானவை",
    "alert.markDone": "முடிந்தது எனக் குறிக்கவும்",
    "alert.resolved": "தீர்க்கப்பட்டது ✓",

    "completeness.title": "வழக்கு முழுமை",
    "completeness.caseComplete": "வழக்கு முழுமையானது",
    "completeness.itemMissing": "1 தகவல் விடுபட்டுள்ளது: முந்தைய ஆய்வுகள்",
    "completeness.askQuestion": "மேலும் 1 கேள்வி கேளுங்கள்",
    "completeness.infoCollected": "100% தகவல் சேகரிக்கப்பட்டது!",
    "card6.title": "இறுதி வழக்கு தாள்",
    "card6.subtitle": "மருத்துவரின் மதிப்பாய்வு மற்றும் உறுதிப்படுத்தலுக்கு தயார்.",
    "card6.caseReady": "வழக்கு தயார்",
    "card6.caseReadyDesc": "அனைத்து முக்கிய தகவல்களும் சேகரிக்கப்பட்டன. மதிப்பாய்வு செய்து உறுதிப்படுத்தவும்.",
    "card6.viewFinal": "இறுதி வழக்கு தாளைக் காண்க",
    "card6.editRequest": "திருத்து / மேலும் தகவல்களைக் கோரு",

    "ribbon.smartQuestions": "புத்திசாலி கேள்விகள்",
    "ribbon.smartQuestionsSub": "தேவையானதை மட்டுமே கேட்கிறது",
    "ribbon.completeHistory": "முழு வரலாறு",
    "ribbon.completeHistorySub": "கடந்த வருகைகள், அறிக்கைகள், மருந்துகள்",
    "ribbon.ayushFocused": "ஆயுஷ் கவனம்",
    "ribbon.ayushFocusedSub": "தசவித பரீட்சை & பிரகிருதி",
    "ribbon.betterDecisions": "சிறந்த முடிவுகள்",
    "ribbon.betterDecisionsSub": "மருத்துவர்கள் மற்றும் நோயாளிகளுக்கு",
    "ribbon.slogan": "முதல் உரையாடலில் இருந்து சிறந்த கவனிப்பு வரை",

    "patient.greeting": "வணக்கம்,",
    "patient.tagline": "உங்கள் தனிப்பயனாக்கப்பட்ட ஆயுஷ் போர்டல்",
    "patient.myHealth": "என் உடல்நலம்",
    "patient.appointments": "முன்பதிவுகள்",
    "patient.medications": "மருந்துகள்",
    "patient.ayushInsights": "ஆயுஷ் நுண்ணறிவு",
    "patient.messages": "செய்திகள்",
    "patient.readinessGauge": "வழக்கு தயார்நிலை",
    "patient.bookConsultation": "ஆலோசனை பதிவு",
    "patient.uploadReport": "ஆவணத்தை பதிவேற்று",
  },
  te: {
    "brand.name": "స్వాస్థ్య సేతు",
    "brand.tagline": "ఆయుష్ ఆసుపత్రుల కోసం AI-ఆధారిత పూర్వ-సంప్రదింపులు",
    "brand.opdLive": "OPD లైవ్",
    "header.searchPlaceholder": "రోగిని వెతకండి (పేరు / ID / మొబైల్)",
    "header.doctorTitle": "వైద్యులు (MD ఆయుర్వేదం)",
    "header.notifications": "వైద్యుల నోటిఫికేషన్లు",
    "header.markAllRead": "అన్నీ చదివినట్లు గుర్తించండి",
    "header.noPatientFound": "OPD క్యూలో రోగులు కనుగొనబడలేదు",

    "nav.home": "హోమ్",
    "nav.patientQueue": "రోగుల క్యూ",
    "nav.consultations": "సంప్రదింపులు",
    "nav.patientHistory": "రోగి చరిత్ర",
    "nav.reports": "నివేదికలు",
    "nav.analytics": "విశ్లేషణలు",
    "nav.settings": "సెట్టింగ్‌లు",
    "nav.traditionalWisdom": "సాంప్రదాయ జ్ఞానం",
    "nav.modernIntelligence": "ఆధునిక మేధస్సు",

    "banner.welcome": "స్వాగతం, డా. మీరా శర్మ",
    "banner.subtitle": "ప్రతి సంప్రదింపును మరింత సంపూర్ణంగా మరియు ఖచ్చితమైనదిగా చేద్దాం.",
    "badge.voiceTouch": "వాయిస్ + టచ్ ఇంటర్‌ఫేస్",
    "badge.multilingual": "బహుభాషా (12+ భాషలు)",
    "badge.ayushSpecific": "ఆయుష్ ప్రత్యేకం",
    "badge.documentIntelligence": "డాక్యుమెంట్ ఇంటెలిజెన్స్",
    "badge.safeSecure": "సురక్షితమైనది",
    "activePatientLabel": "యాక్టివ్ పేషెంట్:",

    "card1.title": "రోగి కేస్-టేకింగ్",
    "card1.subtitle": "రోగి వారి ప్రాధాన్య భాషలో వాయిస్ లేదా టచ్ ద్వారా ఆందోళనలను పంచుకుంటారు.",
    "card1.ageMale": "వయస్సు: 45 | పురుషుడు",
    "card1.startInteraction": "సంభాషణను ప్రారంభించండి",
    "card1.step1": "1. భాషను ఎంచుకోండి",
    "card1.step2": "2. వాయిస్ / టచ్ ఇన్‌పుట్",
    "card1.step2Desc": "రోగి మాట్లాడతారు లేదా ఎంచుకుంటారు",
    "card1.step3": "3. AI ఇంటర్వ్యూ",
    "card1.step3Desc": "ప్రతిస్పందన ఆధారంగా ప్రశ్నలు",
    "card1.step4": "4. కేస్ సారాంశం",
    "card1.step4Desc": "నిర్మాణాత్మక డేటా మరియు ఫలితాలు",

    "card2.title": "AI ప్రాసెసింగ్ & డేటా ప్రవాహం",
    "card2.subtitle": "AI సమాచారాన్ని సేకరిస్తుంది, నిర్వహిస్తుంది.",
    "card2.nlp": "ట్రాన్స్‌క్రిప్షన్ & NLP",
    "card2.nlpSub": "రియల్-టైమ్ స్పీచ్ టు టెక్స్ట్",
    "card2.ayushKb": "ఆయుష్ నాలెడ్జ్ బేస్",
    "card2.ayushKbSub": "ఆయుర్వేద జ్ఞాన వ్యవస్థ",
    "card2.caseSheet": "కేస్ షీట్",
    "card2.caseSheetSub": "ప్రామాణిక OPD ఫార్మాట్",
    "card2.storage": "డేటా నిల్వ",
    "card2.storageSub": "ABHA & EHR కంప్లైంట్",

    "card3.title": "రోగి కేస్ షీట్ (ప్రివ్యూ)",
    "card3.subtitle": "AI-రూపొందించిన సారాంశం. వైద్యులచే సవరించదగినది.",
    "card3.viewFullHistory": "పూర్తి చరిత్రను చూడండి",
    "tab.summary": "సారాంశం",
    "tab.ayushAssessment": "ఆయుష్ అంచనా",
    "tab.medicalHistory": "వైద్య చరిత్ర",
    "tab.reports": "నివేదికలు",
    "field.chiefComplaint": "ప్రధాన సమస్య",
    "field.currentMedicines": "ప్రస్తుత మందులు",
    "field.ayushInsights": "ఆయుష్ అంతర్దృష్టి",
    "field.duration": "వ్యవధి",
    "field.allergies": "అలెర్జీలు",
    "field.prakriti": "ప్రకృతి",
    "field.previousTreatment": "మునుపటి చికిత్స",
    "field.familyHistory": "కుటుంబ చరిత్ర",
    "field.agni": "అగ్ని",

    "card4.title": "డాక్యుమెంట్ ఇంటెలిజెన్స్",
    "card4.subtitle": "నివేదికలను అప్‌లోడ్ చేయండి. AI టైమ్‌లైన్‌ను నిర్మిస్తుంది.",
    "card4.dragDrop": "ఫైల్‌లను ఇక్కడ లాగండి & వదలండి",
    "card4.orBrowse": "లేదా పరికరం నుండి ఎంచుకోండి",
    "card4.uploadBtn": "పత్రాలను అప్‌లోడ్ చేయండి",
    "card4.supports": "PDF, JPG, PNG (గరిష్టంగా 10MB)",
    "docType.prescription": "ప్రిస్క్రిప్షన్",
    "docType.labReport": "ల్యాబ్ రిపోర్ట్",
    "docType.discharge": "డిశ్చార్జ్ సారాంశం",
    "docType.other": "ఇతర పత్రాలు",
    "timeline.title": "వైద్య కాలక్రమం",
    "timeline.chronological": "కాలక్రమానుసారం",

    "card5.title": "డాక్టర్ శ్రద్ధ పెట్టె",
    "card5.subtitle": "మీ దృష్టిని ఆకర్షించే ముఖ్యమైన అంశాలు.",
    "alert.newSymptom": "కొత్త లక్షణం",
    "alert.sleepDisturbance": "నిద్రలేమి",
    "alert.missingReport": "తప్పిపోయిన నివేదిక",
    "alert.prevPrescription": "మునుపటి ప్రిస్క్రిప్షన్",
    "alert.medicineChanged": "మందు మార్చబడింది",
    "alert.addedVitaminD": "విటమిన్ డి జోడించబడింది",
    "alert.noCriticalAlerts": "కీలక హెచ్చరికలు లేవు",
    "alert.vitalSignsNormal": "జీవ సంకేతాలు సాధారణం",
    "alert.markDone": "పూర్తయినట్లు గుర్తించండి",
    "alert.resolved": "పరిష్కరించబడింది ✓",

    "completeness.title": "కేస్ సంపూర్ణత",
    "completeness.caseComplete": "కేస్ పూర్తయింది",
    "completeness.itemMissing": "1 అంశం మిస్సయింది: మునుపటి పరిశోధనలు",
    "completeness.askQuestion": "మరో 1 ప్రశ్న అడగండి",
    "completeness.infoCollected": "100% సమాచారం సేకరించబడింది!",
    "card6.title": "తుది కేస్ షీట్",
    "card6.subtitle": "వైద్యుల సమీక్ష మరియు నిర్ధారణ కోసం సిద్ధంగా ఉంది.",
    "card6.caseReady": "కేస్ సిద్ధంగా ఉంది",
    "card6.caseReadyDesc": "అవసరమైన మొత్తం సమాచారం సేకరించబడింది. సమీక్షించండి మరియు నిర్ధారించండి.",
    "card6.viewFinal": "తుది కేస్ షీట్ చూడండి",
    "card6.editRequest": "సవరించండి / మరింత సమాచారం అడగండి",

    "ribbon.smartQuestions": "స్మార్ట్ ప్రశ్నలు",
    "ribbon.smartQuestionsSub": "అవసరమైన వాటిని మాత్రమే అడుగుతుంది",
    "ribbon.completeHistory": "పూర్తి చరిత్ర",
    "ribbon.completeHistorySub": "గత సందర్శనలు, నివేదికలు, మందులు",
    "ribbon.ayushFocused": "ఆయుష్ దృష్టి",
    "ribbon.ayushFocusedSub": "దశవిధ పరీక్ష & ప్రకృతి",
    "ribbon.betterDecisions": "మంచి నిర్ణయాలు",
    "ribbon.betterDecisionsSub": "వైద్యులు మరియు రోగుల కోసం",
    "ribbon.slogan": "మొదటి పరస్పర చర్య నుండి మెరుగైన సంరక్షణ వరకు",

    "patient.greeting": "నమస్కారం,",
    "patient.tagline": "మీ ఆయుష్ ఆరోగ్య పోర్టల్",
    "patient.myHealth": "నా ఆరోగ్యం",
    "patient.appointments": "అపాయింట్‌మెంట్‌లు",
    "patient.medications": "మందులు",
    "patient.ayushInsights": "ఆయుష్ అంతర్దృష్టి",
    "patient.messages": "సందేశాలు",
    "patient.readinessGauge": "కేస్ సంసిద్ధత",
    "patient.bookConsultation": "సంప్రదింపును బుక్ చేయండి",
    "patient.uploadReport": "రికార్డును అప్‌లోడ్ చేయండి",
  },
  sa: {
    "brand.name": "स्वास्थ्यसेतुः",
    "brand.tagline": "आयुष-रुग्णालयेभ्यः कृत्रिमबुद्धियुक्त-पूर्वपरामर्शः",
    "brand.opdLive": "ओपीडी प्रत्यक्षम्",
    "header.searchPlaceholder": "रोगी अन्विष्यताम् (नाम / संविद् / दूरभाषः)",
    "header.doctorTitle": "वैद्यः (एमडी आयुर्वेदः)",
    "header.notifications": "वैद्य-सूचनाः",
    "header.markAllRead": "सर्वाः पठिताः कुर्वन्तु",
    "header.noPatientFound": "सक्रिय-पङ्क्तौ कोऽपि रोगी न लब्धः",

    "nav.home": "मुख्यपृष्ठम्",
    "nav.patientQueue": "रोगिपङ्क्तिः",
    "nav.consultations": "परामर्शः",
    "nav.patientHistory": "रोगिवृत्तम्",
    "nav.reports": "विवरणपत्राणि",
    "nav.analytics": "विश्लेषणम्",
    "nav.settings": "संयोजनानि",
    "nav.traditionalWisdom": "पारम्परिकं ज्ञानम्",
    "nav.modernIntelligence": "आधुनिकबुद्धिमत्ता",

    "banner.welcome": "स्वागतम्, डॉ. मीरा शर्मा",
    "banner.subtitle": "प्रत्येकं परामर्शं सम्पूर्णं यथार्थं च कुर्मः।",
    "badge.voiceTouch": "वाणी + स्पर्श अन्तरफलकम्",
    "badge.multilingual": "बहुभाषिकम् (१२+ भाषाः)",
    "badge.ayushSpecific": "आयुष-विशिष्टम्",
    "badge.documentIntelligence": "अभिलेख-प्रज्ञा",
    "badge.safeSecure": "सुरक्षितम्",
    "activePatientLabel": "सक्रियरोगी:",

    "card1.title": "रोगिवृत्तसंग्रहः",
    "card1.subtitle": "रोगी स्वप्रियायां भाषायां वाण्या स्पर्शेन वा समस्याः कथयति।",
    "card1.ageMale": "वयः: ४५ | पुरुषः",
    "card1.startInteraction": "संवादं प्रारभताम्",
    "card1.step1": "१. भाषां चिनोतु",
    "card1.step2": "२. वाणी / स्पर्श निवेशः",
    "card1.step2Desc": "रोगी भाषते अथवा चिनोति",
    "card1.step3": "३. एआई साक्षात्कारः",
    "card1.step3Desc": "उत्तरानुसारम् अनुकूली प्रश्नमाला",
    "card1.step4": "४. वृत्तसारः",
    "card1.step4Desc": "संरचितं वृत्तं मुख्यनिष्कर्षश्च",

    "card2.title": "एआई-प्रक्रिया डेटाप्रवाहश्च",
    "card2.subtitle": "एआई ज्ञानम् उद्धरति, संरचयति च।",
    "card2.nlp": "प्रतिलेखनं भाषाप्रक्रिया च",
    "card2.nlpSub": "प्रत्यक्षवाणीतः पाठान्तरणम्",
    "card2.ayushKb": "आयुष ज्ञानकोशः",
    "card2.ayushKbSub": "आयुर्वेदज्ञानव्यवस्था",
    "card2.caseSheet": "संरचिता वृत्तपत्रिका",
    "card2.caseSheetSub": "मानक ओपीडी स्वरूपम्",
    "card2.storage": "डेटा-सङ्ग्रहः",
    "card2.storageSub": "आभा-ईएचआर अनुपालितम्",

    "card3.title": "रोगिवृत्तपत्रिका (पूर्वावलोकनम्)",
    "card3.subtitle": "एआई-निर्मितः संरचितसारः। वैद्यसम्पाद्यः।",
    "card3.viewFullHistory": "सम्पूर्णं वृत्तं पश्यतु",
    "tab.summary": "संक्षेपः",
    "tab.ayushAssessment": "आयुष-परीक्षणम्",
    "tab.medicalHistory": "चिकित्सावृत्तम्",
    "tab.reports": "अभिलेखपत्राणि",
    "field.chiefComplaint": "मुख्या वेदना",
    "field.currentMedicines": "वर्तमानौषधानि",
    "field.ayushInsights": "आयुष-अन्तर्दृष्टिः",
    "field.duration": "अवधिः",
    "field.allergies": "असात्म्यता (एलर्जी)",
    "field.prakriti": "प्रकृतिः",
    "field.previousTreatment": "पूर्वं कृतोपचारः",
    "field.familyHistory": "कुलवृत्तम्",
    "field.agni": "अग्निः",

    "card4.title": "अभिलेख-प्रज्ञा",
    "card4.subtitle": "विवरणपत्राणि आरोपयन्तु। एआई कालक्रमं रचयति।",
    "card4.dragDrop": "अत्र पत्राणि समर्पयन्तु",
    "card4.orBrowse": "अथवा यन्त्रात् चिनोतु",
    "card4.uploadBtn": "अभिलेखान् आरोपयन्तु",
    "card4.supports": "PDF, JPG, PNG समर्थितम् (१०MB पर्यन्तम्)",
    "docType.prescription": "व्यवस्थापत्रम् (पर्चा)",
    "docType.labReport": "प्रयोगशाला-विवरणम्",
    "docType.discharge": "मुक्तिपत्रसारः",
    "docType.other": "इतराणि पत्राणि",
    "timeline.title": "चिकित्सा-कालक्रमः",
    "timeline.chronological": "कालक्रमेण",

    "card5.title": "वैद्य-सावधानता-कोष्ठकम्",
    "card5.subtitle": "ध्यानावश्यकाः मुख्याः बिन्दवः।",
    "alert.newSymptom": "नूतनं लक्षणम्",
    "alert.sleepDisturbance": "निद्राभङ्गः",
    "alert.missingReport": "अनुपलब्धं विवरणपत्रम्",
    "alert.prevPrescription": "पूर्वतनं व्यवस्थापत्रम्",
    "alert.medicineChanged": "औषधं परिवर्तितम्",
    "alert.addedVitaminD": "विटामिन-डी योजितम्",
    "alert.noCriticalAlerts": "कोऽपि सङ्कटनास्ति",
    "alert.vitalSignsNormal": "प्राणसंकेताः सामान्याः",
    "alert.markDone": "समाप्तं कुरु",
    "alert.resolved": "समाहितम् ✓",

    "completeness.title": "वृत्तसम्पूर्णता",
    "completeness.caseComplete": "वृत्तं सम्पन्नम्",
    "completeness.itemMissing": "१ विषयः अवशिष्टः: पूर्वतनपरीक्षणाः",
    "completeness.askQuestion": "अपरं १ प्रश्नं पृच्छतु",
    "completeness.infoCollected": "१००% वृत्तं सङ्गृहीतम्!",
    "card6.title": "अन्तिमा वृत्तपत्रिका",
    "card6.subtitle": "वैद्यसमीक्षा-पुष्टीकरणाभ्यां सज्जा।",
    "card6.caseReady": "वृत्तं सज्जम्",
    "card6.caseReadyDesc": "सर्वाः मुख्याः सूचनाः सङ्गृहीताः। कृपया समीक्ष्य पुष्टिकरोतु।",
    "card6.viewFinal": "अन्तिमां पत्रिकां पश्यतु",
    "card6.editRequest": "सम्पादयतु / अधिकं पृच्छतु",

    "ribbon.smartQuestions": "चतुराः प्रश्नाः",
    "ribbon.smartQuestionsSub": "आवश्यकमेव पृच्छति",
    "ribbon.completeHistory": "सम्पूर्णं वृत्तम्",
    "ribbon.completeHistorySub": "पूर्वागताः, पत्राणि, औषधानि",
    "ribbon.ayushFocused": "आयुष-केन्द्रितम्",
    "ribbon.ayushFocusedSub": "दशविधपरीक्षा प्रकृतिश्च",
    "ribbon.betterDecisions": "श्रेष्ठाः निर्णयाः",
    "ribbon.betterDecisionsSub": "वैद्येभ्यः रोगिभ्यश्च",
    "ribbon.slogan": "प्रथमालापात् श्रेष्ठशुश्रूषां यावत्",

    "patient.greeting": "नमस्ते,",
    "patient.tagline": "भवतः व्यक्तिगतं आयुष-स्वास्थ्य-जालस्थलम्",
    "patient.myHealth": "मम स्वास्थ्यम्",
    "patient.appointments": "मेलननिश्चयाः",
    "patient.medications": "औषधानि",
    "patient.ayushInsights": "आयुष-अन्तर्दृष्टिः",
    "patient.messages": "सन्देशाः",
    "patient.readinessGauge": "वृत्तसज्जीभावः",
    "patient.bookConsultation": "परामर्शं निश्चिनोतु",
    "patient.uploadReport": "आरोग्यपत्रं समर्पयतु",
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  currentLanguage: LanguageOption;
  supportedLanguages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("en");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("swasthya_setu_lang") as LanguageCode;
      if (saved && TRANSLATIONS[saved]) {
        setLanguageState(saved);
      }
    } catch (e) {
      console.warn("Could not read language from localStorage", e);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("swasthya_setu_lang", lang);
    } catch (e) {
      console.warn("Could not save language to localStorage", e);
    }
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const enDict = TRANSLATIONS.en;
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return fallback || key;
  };

  const currentLanguage =
    SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        currentLanguage,
        supportedLanguages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
